# Generated by Django 4.2.1 on 2023-05-15 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App_User', '0001_initial'),
        ('App_Project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_User.employee')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_Project.task')),
            ],
        ),
    ]
