# Generated by Django 4.2.1 on 2023-05-27 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App_User', '0001_initial'),
        ('App_Project', '0003_rename_employee_employeetask_employees'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employees', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_User.employee')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_Project.project')),
            ],
        ),
        migrations.AddField(
            model_name='employeetask',
            name='employee_project',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='App_Project.employeeproject'),
            preserve_default=False,
        ),
    ]
