# Generated by Django 4.2.1 on 2023-06-13 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App_Project', '0005_remove_assignedtask_assigned_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeetask',
            name='employee_project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='App_Project.employeeproject'),
        ),
    ]
