# Generated by Django 4.2.1 on 2023-06-13 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App_Project', '0006_alter_employeetask_employee_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeetask',
            name='employee_project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='App_Project.project'),
        ),
    ]
